baseURL = 'https://nginx.org/'
languageCode = 'en-us'
title = 'nginx'

[module]
  [[module.imports]]
    path="/Users/m.mckeen/Desktop/Projects/nginx/nginx-github/nginx-hugo-theme"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source       = "hugo_stats.json"
    target       = "assets/notwatching/hugo_stats.json"
    disableWatch = true

[build.buildStats]
  enable = true
  [[build.cachebusters]]
    source = "assets/notwatching/hugo_stats\\.json"
    target = "css"